import Blockquote from "@/components/Blockquote";
import Head from "next/head";
import Link from "@/components/Link";
import pagetitle from "@/utils/pagetitle";

const Legal = () => {
  const title = pagetitle("Legal");

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta content={title} property="og:title" />
        <meta content={title} name="twitter:title" />
      </Head>
      <article className="text-left flex flex-col gap-4">
        <h1 className="text-3xl font-bold">Legal disclaimers</h1>
        <p>
          This website uses images and content from World of Warcraft and
          associated materials. All rights to such images and content are
          reserved by Blizzard Entertainment. This website is not affiliated
          with Blizzard Entertainment in any way.
        </p>
        <p>
          We strive to be compliant with Blizzard Entertainment&apos;s legal
          policies, and rely on the following terms.
        </p>
        <Blockquote
          cite={
            <>
              <Link
                className="text-green"
                href="https://www.blizzard.com/en-us/legal/28d5ebbf-c245-4408-8ba9-043dd5f056bf/legal-faq#1662876719"
              >
                Blizzard Entertainment - Legal FAQ
              </Link>{" "}
              <small className="flex-grow text-right">
                Snapshot from 2023-04-27
              </small>
            </>
          }
          className="text-light"
        >
          <p>
            Blizzard Entertainment® hereby grants you a personal, non-exclusive,
            non-transferable and non- assignable license to use and display, for
            home, noncommercial and personal use only, one copy of any material
            and/or software that you may download from this site, including, but
            not limited to, any files, codes, audio or images incorporated in or
            generated by the software (collectively the &quot;Downloaded
            Content&quot;) provided, however, that you must include or maintain
            all copyright and other notices contained or associated with such
            Downloaded Content. You acknowledge and agree that you may not
            sublicense, assign or otherwise transfer this license or the
            Downloaded Content and that no title to the Downloaded Content has
            been or will be transferred to you from Blizzard Entertainment® or
            anyone else. You also agree that you will not alter, disassemble,
            decompile, reverse engineer or otherwise modify the Downloaded
            Content.
          </p>
          <p>
            Also, we reserve the right to revoke this limited use license at any
            time, for any reason, and at the sole discretion of Blizzard
            Entertainment®. You may not use our materials on sites that feature
            defamatory pornographic, or inflammatory content, including, but not
            limited to, hacks and cheats for any of our games or any other
            content that Blizzard Entertainment® find objectionable or unlawful.
          </p>
        </Blockquote>
        <p>
          In the pursuit of compliance with the above policies we will dedicate
          some space below to mapping out the images and content used on this
          website and their sources.
        </p>
        <h2 className="text-2xl">
          <Link href="#images">Images</Link>
        </h2>
      </article>
    </>
  );
};

export default Legal;
